# Generated by Django 2.2 on 2019-06-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
    ]
