# Generated by Django 2.2 on 2019-06-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_category_segment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='segment',
            options={'verbose_name': 'Сегмент', 'verbose_name_plural': 'Сегменты'},
        ),
        migrations.AddField(
            model_name='category',
            name='competition',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='competitions.Competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segment',
            name='category',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='competitions.Competition'),
            preserve_default=False,
        ),
    ]
