# Generated by Django 2.2 on 2019-06-01 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_auto_20190601_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='competitions.Category'),
        ),
    ]
