# Generated by Django 2.2 on 2019-06-01 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_auto_20190601_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='liveVideoLink',
            field=models.TextField(default='null', validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
