# Generated by Django 2.2 on 2019-06-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_competition_livevideolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='annonce',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
