# Generated by Django 2.2 on 2019-06-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_competition_annonce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('centerX', models.CharField(max_length=100)),
                ('centerY', models.CharField(max_length=100)),
                ('zoom', models.PositiveSmallIntegerField(default=12)),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
    ]
