# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.2 on 2019-03-22 22:43
=======
# Generated by Django 1.11.2 on 2019-03-27 20:34
>>>>>>> stage_one
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
=======
import django.utils.timezone
>>>>>>> stage_one


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
<<<<<<< HEAD
=======
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
>>>>>>> stage_one
            ],
        ),
        migrations.AddField(
            model_name='entry',
<<<<<<< HEAD
            name='master_class',
=======
            name='master_class_id',
>>>>>>> stage_one
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.MasterClass'),
        ),
    ]
