# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-22 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='user_id',
        ),
    ]
