# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-23 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='master_class',
            new_name='master_class_id',
        ),
    ]
