# Generated by Django 2.2 on 2019-07-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField(null=True, verbose_name='date published')),
                ('image', models.ImageField(null=True, upload_to='static/uploads/img')),
            ],
        ),
    ]
