# Generated by Django 2.1.7 on 2019-03-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190326_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='date_end',
            field=models.DateTimeField(default='01/01/2019'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='date_start',
            field=models.DateTimeField(default='01/01/2019'),
        ),
    ]
