# Generated by Django 2.2 on 2019-07-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_coach_mediaimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='locationX',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camp',
            name='locationY',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camp',
            name='locationZoom',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
