# Generated by Django 2.1.7 on 2019-03-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190326_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='date_end',
            field=models.DateTimeField(default='2019-01-01'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='date_start',
            field=models.DateTimeField(default='2019-01-01'),
        ),
    ]
