# Generated by Django 2.2 on 2019-05-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190516_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='seats',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
