# Generated by Django 2.1.7 on 2019-03-26 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20190326_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='date_end',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='date_start',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
