# Generated by Django 2.2 on 2019-05-19 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_masterclass_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Сборы',
                'verbose_name_plural': 'Сборы',
            },
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='seats',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
