# Generated by Django 2.2 on 2019-07-13 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_albom'),
    ]

    operations = [
        migrations.AddField(
            model_name='albom',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Camp'),
        ),
    ]
