# Generated by Django 2.1.7 on 2019-03-26 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20190326_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='date_end',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='date_start',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
