# Generated by Django 2.2 on 2019-07-13 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_albom_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaimage',
            name='albom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.Albom'),
        ),
    ]
