# Generated by Django 2.2 on 2019-05-19 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20190519_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='camp',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
