# Generated by Django 2.2 on 2019-05-19 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20190519_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='camp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.Camp'),
            preserve_default=False,
        ),
    ]
