# Generated by Django 2.2 on 2019-05-19 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20190519_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
