# Generated by Django 2.2 on 2019-07-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_teamcoaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
